image: ioribranford/godot-docker:3.1

stages:
        - build

.build:
        <<: &build
                stage: build
                before_script:
                        - ./configure.sh
                script:
                        - godot --export${DEBUG_OPTION} "${EXPORT}" "${CI_PROJECT_NAME}.${BINEXT}"
                after_script:
                        - find -name "*.${BINEXT}"
                artifacts:
                        name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${PLATFORM}"
                        paths:
                                - "${CI_PROJECT_NAME}.pck"
                                - "${CI_PROJECT_NAME}.${BINEXT}"

build:linux:
        <<: *build
        variables:
                EXPORT: "Linux/X11"
                BINEXT: "x86_64"
                PLATFORM: "linux"

build:windows:
        <<: *build
        image: ioribranford/godot-docker:3.1-windows
        variables:
                EXPORT: "Windows Desktop"
                BINEXT: "exe"
                PLATFORM: "windows"

build:macosx:
        <<: *build
        variables:
                EXPORT: "Mac OSX"
                BINEXT: "app"
                PLATFORM: "macosx"
        after_script:
                - mv "${CI_PROJECT_NAME}.${BINEXT}" app.zip # actually zip containing app
                - unzip app.zip
                - find -name "*.${BINEXT}"
        artifacts:
                name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${PLATFORM}"
                paths:
                        - "*.${BINEXT}"
                          # pck is inside the app folder

build:android:
        <<: *build
        image: ioribranford/godot-docker:3.1-android
        variables:
                EXPORT: "Android"
                BINEXT: "apk"
                PLATFORM: "android"
                #DEBUG_OPTION: "-debug"
        artifacts:
                name: "${CI_PROJECT_NAME}-${CI_COMMIT_REF_NAME}-${PLATFORM}"
                paths:
                        - "*.${BINEXT}"
